name: Actualizar news.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar script de actualización
        run: node scripts/update-news.js

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "chore: actualización automática de news.json" || echo "Sin cambios"
          git push
