name: Actualizar news.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Generar news.json
        run: node fetch-news.cjs

      - name: Commit y push si hay cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'build: actualizar news.json'
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
          branch: main
